---
- name: Install Operating System Components
  ansible.builtin.include_tasks: os.yml
  args:
    apply:
      become: true

- name: Execute Podman Actions
  ansible.builtin.include_tasks: podman.yml
  args:
    apply:
      become: true
  vars:
    tpa_single_node_registry_username: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_USERNAME') }}"
    tpa_single_node_registry_password: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_PASSWORD') }}"
    tpa_single_node_csub_secret_manifest: "{{ lookup('ansible.builtin.env', 'GUAC_CSUB_SECRET_FILE') }}"
