- name: Trustification
  hosts: trustification
  vars:
    tpa_single_node_base_hostname: trustification
    tpa_single_node_skip_os_install: true
    tpa_single_node_config_dir: /etc/rhtpa
    tpa_single_node_certs_dir: "{{ tpa_single_node_config_dir }}/certs"
    tpa_single_node_kube_manifest_dir: "{{ tpa_single_node_config_dir }}/manifests"
    tpa_single_node_kube_configmap_dir: "{{ tpa_single_node_config_dir }}/configs"
    # * tpa_single_node_registry_username
    #   * get at https://access.redhat.com/terms-based-registry
    tpa_single_node_registry_username: <YOUR_USERNAME>
    # * tpa_single_node_registry_password
    #   * get at https://access.redhat.com/terms-based-registry
    tpa_single_node_registry_password: <YOUR_PASSWORD>
    tpa_single_node_podman_network: tcnet
    tpa_single_node_trustification_image:
    tpa_single_node_guac_image:
    # REMOVE TO USE EXTERNAl SERVICES
    tpa_single_node_sso_image:
    tpa_single_node_postgresql:
    tpa_single_node_streams_kafka:
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
