---
- name: Configure OIDC
  ansible.builtin.include_tasks: infra/oidc.yml

#   ansible.builtin.include_tasks: infra/trust_anchor.yml

# - name: Configure TLS certs
#   ansible.builtin.include_tasks: infra/tls_cert.yml

- name: Configure db
  ansible.builtin.include_tasks: infra/db.yml
  args:
    apply:
      become: true

- name: Migrate db
  ansible.builtin.include_tasks: infra/migrate-db.yml

- name: Create configmap auth for server
  ansible.builtin.include_tasks: infra/component_auth.yml
  vars:
    component:
      name: "server"
      type: "api"
