---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tpa_single_node_base_hostname is defined
      - tpa_single_node_base_hostname | trim | length > 0
    msg: "'tpa_single_node_base_hostname' must be specified"

- name: Get RHTPA network details
  containers.podman.podman_network:
    name: "{{ tpa_single_node_podman_network }}"
  register: tpa_podman_network_results

- name: Set DNS Resolver
  ansible.builtin.set_fact:
    dns_resolver: "{{ tpa_podman_network_results.network.subnets[0].gateway }}"

- name: Copy init-db.sql to Server
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'configs/init-db.sql') }}"
    dest: "/tmp/init-db.sql"
    remote_src: true
    mode: "0600"

- name: Run init-db.sql
  ansible.builtin.command: "psql postgresql://{{ tpa_single_node_pg_user }}:{{ tpa_single_node_pg_user_passwd }}@{{ tpa_single_node_pg_host }}/\n
  {{ tpa_single_node_pg_db }} -v ON_ERROR_STOP=1 \n
  -v db_name={{ tpa_single_node_pg_db }} -v db_user={{ tpa_single_node_pg_user }} \n
  -v db_password={{ tpa_single_node_pg_user_passwd }} -f /tmp/init-db.sql"
  changed_when: false
