kind: Deployment
metadata:
  name: collector-osv
  labels:
    app.kubernetes.io/name: collector-osv
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: redhat-trusted-profile-analyzer
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/part-of: trusted-profile-analyzer
  annotations: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collector-osv
      app.kubernetes.io/component: collector
      app.kubernetes.io/instance: redhat-trusted-profile-analyzer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collector-osv
        app.kubernetes.io/component: collector
        app.kubernetes.io/instance: redhat-trusted-profile-analyzer
      annotations:
        configHash/auth: dac9d88322da8b671d9fc4f81500698ea05f108df8784b66db80d4242c9dee06
    spec:
      containers:
        - name: service
          image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9@sha256:044b6070e52378a93cbcd65cbd5d10b866f102ee8d6040b92147df7b52202e83
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 2
            httpGet:
              path: /health/live
              port: 9010
          readinessProbe:
            initialDelaySeconds: 2
            httpGet:
              path: /health/ready
              port: 9010
          command:
            - /trust
          args:
            - collector
            - osv
            - -p
            - '8080'
            - --auth-configuration
            - /etc/config/auth.yaml
            - --v11y-url
            - https://v11y-api.trustificcation.svc.cluster.local
            - --guac-url
            - https://guac-graphql.trustificcation.svc.cluster.local/query
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RUST_LOG
              value: info
            - name: INFRASTRUCTURE_ENABLED
              value: 'true'
            - name: INFRASTRUCTURE_BIND
              value: '[::]:9010'
            - name: HTTP_SERVER_BIND_ADDR
              value: '::'
            - name: HTTP_SERVER_TLS_ENABLED
              value: 'true'
            - name: HTTP_SERVER_TLS_KEY_FILE
              value: /etc/tls/tls.key
            - name: HTTP_SERVER_TLS_CERTIFICATE_FILE
              value: /etc/tls/tls.crt
            - name: OIDC_PROVIDER_CLIENT_ID
              value: walker
            - name: OIDC_PROVIDER_CLIENT_SECRET
              value: 6560cc91-4e20-4edd-881c-b15b169f8a80
            - name: OIDC_PROVIDER_ISSUER_URL
              value: https://sso$APP_DOMAIN_URL/realms/chicken
            - name: CLIENT_TLS_CA_CERTIFICATES
              value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          volumeMounts:
            - name: guac-config
              mountPath: /guac
              readOnly: true
            - mountPath: /etc/tls
              name: tls
              readOnly: true
            - name: config-auth
              mountPath: /etc/config/auth.yaml
              subPath: auth.yaml
          ports:
            - containerPort: 9010
              protocol: TCP
              name: infra
            - containerPort: 8080
              name: endpoint
              protocol: TCP
      volumes:
        - name: guac-config
          configMap:
            name: collectorist-api
        - name: tls
          secret:
            secretName: collector-osv-tls
        - name: config-auth
          configMap:
            name: collector-osv-auth
