kind: Service
metadata:
  name: collector-osv
  labels:
    app.kubernetes.io/name: collector-osv
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: redhat-trusted-profile-analyzer
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/part-of: trusted-profile-analyzer
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: collector-osv-tls
spec:
  ports:
    - name: endpoint
      port: 443
      protocol: TCP
      targetPort: endpoint
  selector:
    app.kubernetes.io/name: collector-osv
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: redhat-trusted-profile-analyzer
  type: ClusterIP
