- name: Verify
  hosts: molecule
  gather_facts: true
  become: true
  vars:
    test_dir_path: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../vm-testing/test"
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Get IP of the current node
      # The tasks below run locally, so their ansible_ssh_host is 127.0.0.1
      ansible.builtin.set_fact:
        node_ip: "{{ ansible_ssh_host }}"

    - name: Build the test Podman image
      containers.podman.podman_image:
        name: fedora-cosign
        tag: latest
        pull: false
        force: true
        path: "{{ test_dir_path }}"
        build:
          cache: true
          file: "Containerfile"
      become: false
      delegate_to: localhost
