---
- name: Generate Guac graphql secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/guac/graphql/Secret.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/Secrets/guac-graphql.yaml"
    mode: "0600"

- name: Play Guac graphql secret manifest
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_kube_manifest_dir }}/Secrets/guac-graphql.yaml"
  changed_when: true

- name: Deploy guac-graphql Pod
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: guac-graphql
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/guac/graphql/Deployment.yaml.j2') | from_yaml }}"
