kind: CronJob
metadata:
  name: bombastic-walker
  labels:
    app.kubernetes.io/name: bombastic-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: trustification
spec:
  schedule: ${BOMBASTIC_WALKER_SCHEDULE}
  suspend: ${{BOMBASTIC_WALKER_SUSPEND}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: bombastic-walker
            app.kubernetes.io/component: walker
            app.kubernetes.io/part-of: trustification
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: walker-state
              persistentVolumeClaim:
                claimName: bombastic-walker-state
          containers:
            - image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9@sha256:044b6070e52378a93cbcd65cbd5d10b866f102ee8d6040b92147df7b52202e83
              imagePullPolicy: Always
              name: walker
              command:
                - /trust
              args:
                - bombastic
                - walker
                - --sink
                - https://sbom.${DOMAIN}
                - --source
                - https://access.redhat.com/security/data/sbom/beta/
                - '-3'
                - --signing-key
                - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
                - --fix-licenses
                - 'true'
                - --since-file
                - /walker-state/since
              env:
                - name: RUST_LOG
                  value: ${LOG_LEVEL}
                - name: INFRASTRUCTURE_ENABLED
                  value: 'true'
                - name: INFRASTRUCTURE_BIND
                  value: '[::]:9010'
                - name: OIDC_PROVIDER_CLIENT_ID
                  value: trusted-content-api
                - name: OIDC_PROVIDER_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: ${OIDC_PROVIDER_CLIENT_SECRET_KEY}
                      name: ${OIDC_PROVIDER_CLIENT_SECRET_NAME}
                - name: OIDC_PROVIDER_ISSUER_URL
                  value: ${ISSUER_URL}
              ports:
                - containerPort: 9010
                  protocol: TCP
                  name: infra
              volumeMounts:
                - mountPath: /walker-state
                  name: walker-state
              resources: ${{BOMBASTIC_WALKER_RESOURCES}}
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 9010
                initialDelaySeconds: 2
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 9010
                initialDelaySeconds: 2
              startupProbe:
                httpGet:
                  path: /health/startup
                  port: 9010
